version: '3.9'

services:

  db:
    image: postgres
    restart: always    
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pwd_admin_i
      POSTGRES_DB: my_db
      POSTGRES_USER: admin_i
	ports:
      - 5432:5432
	volumes:
      - ./pg-data/mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
